/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/otp/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send a sign-in code by SMS */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        phone: string;
                    };
                };
            };
            responses: {
                /** @description Code sent */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Rate limited */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/otp/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify the code and receive a token */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        phone: string;
                        code: string;
                    };
                };
            };
            responses: {
                /** @description Authenticated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            token?: string;
                            user?: components["schemas"]["Me"];
                        };
                    };
                };
                /** @description Wrong or expired code */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sponsor/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a diaspora sponsor account */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name: string;
                        /** Format: email */
                        email: string;
                        password: string;
                    };
                };
            };
            responses: {
                /** @description Registered */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            token?: string;
                            user?: components["schemas"]["Me"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sponsor/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sponsor email sign-in */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: email */
                        email: string;
                        password: string;
                    };
                };
            };
            responses: {
                /** @description Authenticated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            token?: string;
                            user?: components["schemas"]["Me"];
                        };
                    };
                };
                /** @description Invalid credentials */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current user */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Profile */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Me"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update profile (name, locale) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        name?: string;
                        /** @enum {string} */
                        locale?: "en" | "pcm";
                    };
                };
            };
            responses: {
                /** @description Updated profile */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Me"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/consents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current consent state per kind */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Consent map */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConsentMap"];
                    };
                };
            };
        };
        put?: never;
        /** Grant or revoke a consent (append-only ledger) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        kind: components["schemas"]["ConsentKind"];
                        granted: boolean;
                    };
                };
            };
            responses: {
                /** @description New consent map */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConsentMap"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/consults": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The patient's consults (latest 20) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Consult list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Consult"][];
                    };
                };
            };
        };
        put?: never;
        /** Start a consult from triage intake */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        complaint: string;
                        answers?: {
                            [key: string]: boolean;
                        };
                        dependant_id?: string | null;
                    };
                };
            };
            responses: {
                /** @description Created (state=triaged awaiting payment, queued, or escalated) */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Consult"];
                    };
                };
                /** @description Telemedicine consent required (code=consent_required) */
                428: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/consults/{consult}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One consult (participants + staff only; PHI-logged) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    consult: components["parameters"]["consultId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Consult */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Consult"];
                    };
                };
                /** @description Not a participant */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/consults/{consult}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Thread messages (PHI-logged) */
        get: {
            parameters: {
                query?: {
                    /** @description Only messages with id greater than this */
                    after?: string;
                };
                header?: never;
                path: {
                    consult: components["parameters"]["consultId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Messages */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Message"][];
                    };
                };
            };
        };
        put?: never;
        /** Send a message into the thread */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    consult: components["parameters"]["consultId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        body: string;
                        /** @enum {string} */
                        kind?: "text" | "image" | "voice_note";
                    };
                };
            };
            responses: {
                /** @description Sent */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not a participant */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/consults/{consult}/pay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pay the consult fee (idempotent) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    consult: components["parameters"]["consultId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Payment (fake gateway settles synchronously; real gateways return checkout_url) */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Payment"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments/{payment}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One payment (owner only) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    payment: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Payment */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Payment"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/prescriptions/{prescription}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One prescription (PHI-logged) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    prescription: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Prescription */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Prescription"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dependants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The patient's dependants */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Dependants */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Dependant"][];
                    };
                };
            };
        };
        put?: never;
        /** Add a dependant */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name: string;
                        /** @enum {string} */
                        relationship: "child" | "parent" | "spouse" | "other";
                        /** Format: date */
                        date_of_birth?: string | null;
                        /** @enum {string|null} */
                        sex?: "female" | "male" | null;
                    };
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Dependant"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sponsorships": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sponsorship invitations/links for the signed-in patient */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Sponsorships */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id?: string;
                            sponsor_name?: string;
                            status?: components["schemas"]["SponsorshipStatus"];
                        }[];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sponsorships/{sponsorship}/respond": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept or decline a sponsorship invitation */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    sponsorship: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        accept: boolean;
                    };
                };
            };
            responses: {
                /** @description Responded */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sponsor/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sponsor dashboard (wallet + beneficiaries) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Overview */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SponsorOverview"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sponsor/beneficiaries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Invite a beneficiary by phone (SMS sent; idempotent) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        phone: string;
                        label: string;
                    };
                };
            };
            responses: {
                /** @description Invited */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sponsor/wallet/topup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Top up the care wallet */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        amount_kobo: number;
                    };
                };
            };
            responses: {
                /** @description Payment started (or settled, fake gateway) */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id?: string;
                            status?: string;
                            checkout_url?: string | null;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/booking/doctors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Doctors currently taking bookings, with next free slot */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Bookable doctors */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id?: string;
                            name?: string;
                            /** Format: date-time */
                            next_slot?: string;
                        }[];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/booking/doctors/{doctor}/slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Free slots for a doctor on a local date */
        get: {
            parameters: {
                query: {
                    date: string;
                };
                header?: never;
                path: {
                    doctor: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Slots (UTC instants) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Slot"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The patient's bookings */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Bookings */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Booking"][];
                    };
                };
            };
        };
        put?: never;
        /** Book a slot */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        doctor_id: string;
                        /** Format: date-time */
                        starts_at: string;
                        complaint?: string | null;
                    };
                };
            };
            responses: {
                /** @description Confirmed */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Booking"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings/{booking}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel (patient cutoff enforced) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    booking: components["parameters"]["bookingId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Cancelled */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings/{booking}/reschedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reschedule (atomic cancel + rebook) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    booking: components["parameters"]["bookingId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: date-time */
                        starts_at: string;
                    };
                };
            };
            responses: {
                /** @description Replacement booking */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Booking"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/doctor/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Waiting consults, oldest first (doctor only) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Queue */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id?: string;
                            /** Format: date-time */
                            queued_at?: string;
                            waiting_minutes?: number;
                        }[];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/doctor/consults/{consult}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept a queued consult (licence-gated) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    consult: components["parameters"]["consultId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description In consult */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/doctor/consults/{consult}/conclude": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Conclude the consult (credits earnings for paid consults) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    consult: components["parameters"]["consultId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Concluded */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/doctor/consults/{consult}/prescriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Issue a prescription */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    consult: components["parameters"]["consultId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        items: {
                            formulary_item_id: number;
                            dosage: string;
                            duration_days: number;
                            instructions?: string | null;
                        }[];
                    };
                };
            };
            responses: {
                /** @description Issued */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Prescription"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/doctor/earnings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Earnings summary (doctor only) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Summary */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            pending_kobo?: number;
                            paid_kobo?: number;
                            pending_display?: string;
                            paid_display?: string;
                            recent?: {
                                consult_id?: string;
                                amount_kobo?: number;
                                /** @enum {string} */
                                status?: "pending" | "paid";
                                /** Format: date-time */
                                earned_at?: string;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/doctor/availability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Weekly availability templates (doctor only) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Templates */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AvailabilityTemplate"][];
                    };
                };
            };
        };
        /** Replace the weekly template wholesale */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        templates: components["schemas"]["AvailabilityTemplate"][];
                    };
                };
            };
            responses: {
                /** @description Saved */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/doctor/agenda": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Booked appointments for a local date (default today) */
        get: {
            parameters: {
                query?: {
                    date?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Agenda */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/doctor/bookings/{booking}/begin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Begin the booked consult (window-gated; bypasses the queue) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    booking: components["parameters"]["bookingId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Consult started */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            consult_id?: string;
                            state?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/formulary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Formulary search for the prescribe autocomplete (doctor only) */
        get: {
            parameters: {
                query?: {
                    q?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Items */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id?: number;
                            label?: string;
                        }[];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Me: {
            id?: number;
            name?: string;
            phone?: string | null;
            /** @enum {string} */
            role?: "patient" | "doctor" | "sponsor" | "staff";
            /** @enum {string} */
            locale?: "en" | "pcm";
        };
        /** @enum {string} */
        ConsentKind: "telemedicine_terms" | "privacy_policy" | "sponsor_visibility";
        ConsentMap: {
            telemedicine_terms?: boolean;
            privacy_policy?: boolean;
            sponsor_visibility?: boolean;
        };
        Consult: {
            id?: string;
            /** @enum {string} */
            state?: "requested" | "triaged" | "queued" | "assigned" | "in_consult" | "concluded" | "closed" | "escalated_emergency" | "abandoned";
            /** @enum {string} */
            modality?: "chat" | "voice" | "video";
            queue_position?: number | null;
            doctor?: {
                name?: string;
            } | null;
            for_dependant?: {
                id?: string;
                name?: string | null;
            } | null;
            /** Format: date-time */
            created_at?: string;
        };
        Message: {
            id?: string;
            /** @enum {string} */
            kind?: "text" | "image" | "voice_note" | "system" | "prescription";
            body?: string;
            sender_id?: number | null;
            mine?: boolean;
            /** Format: date-time */
            created_at?: string;
        };
        Payment: {
            id?: string;
            /** @enum {string} */
            status?: "pending" | "succeeded" | "failed" | "refunded";
            amount_kobo?: number;
            amount_display?: string;
            currency?: string;
            reference?: string;
            checkout_url?: string | null;
            consult_id?: string | null;
        };
        Prescription: {
            id?: string;
            /** @enum {string} */
            status?: "issued" | "dispensed" | "cancelled";
            pickup_code?: string;
            doctor?: {
                name?: string;
            } | null;
            items?: {
                medicine?: string;
                dosage?: string;
                duration_days?: number;
                instructions?: string | null;
            }[];
            /** Format: date-time */
            created_at?: string;
        };
        Dependant: {
            id?: string;
            name?: string;
            /** @enum {string} */
            relationship?: "child" | "parent" | "spouse" | "other";
            /** Format: date */
            date_of_birth?: string | null;
            sex?: string | null;
        };
        /** @enum {string} */
        SponsorshipStatus: "pending" | "active" | "declined" | "paused";
        SponsorOverview: {
            wallet_balance_kobo?: number;
            wallet_display?: string;
            beneficiaries?: {
                sponsorship_id?: string;
                label?: string;
                phone?: string;
                status?: components["schemas"]["SponsorshipStatus"];
                care_visible?: boolean;
                last_consult?: {
                    state?: string;
                    /** Format: date-time */
                    at?: string;
                } | null;
            }[];
        };
        Slot: {
            /** Format: date-time */
            starts_at?: string;
            /** Format: date-time */
            ends_at?: string;
        };
        Booking: {
            id?: string;
            /** @enum {string} */
            state?: "confirmed" | "completed" | "cancelled" | "no_show";
            /** Format: date-time */
            starts_at?: string;
            /** Format: date-time */
            ends_at?: string;
            doctor?: {
                id?: string;
                name?: string;
            };
            consult_id?: string | null;
        };
        AvailabilityTemplate: {
            /** @description ISO — 1=Monday */
            weekday: number;
            /** @example 09:00 */
            start_time: string;
            /** @example 12:00 */
            end_time: string;
            /** @enum {integer} */
            slot_minutes: 10 | 15 | 20 | 30 | 45 | 60;
        };
    };
    responses: never;
    parameters: {
        consultId: string;
        bookingId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
